from __future__ import annotations
"""
Lead Engine Orchestrator
========================
Exports DIRECTLY in LeadsFlow import format — columns match
the official template (leads_import_template.csv) exactly.
"""

import csv
import importlib
import re
import uuid
from datetime import datetime
from pathlib import Path
from typing import Optional

from app.models.lead_dataclass import Lead
from app.services.lead_scorer import rank_leads, print_scorecard

try:
    import pandas as pd
    from openpyxl.styles import PatternFill, Font, Alignment, Border, Side
    HAS_PANDAS = True
except ImportError:
    HAS_PANDAS = False


# ── Source registry ───────────────────────────────────────────────────────────
# Maps source key → (display label, module path, class name)

SOURCES = {
    "google":      ("Google Maps",  "app.scrapers.google",      "GoogleMapsScraper"),
    "yelp":        ("Yelp",         "app.scrapers.yelp",        "YelpScraper"),
    "yellowpages": ("Yellow Pages", "app.scrapers.yellowpages", "YellowPagesScraper"),
    "bbb":         ("BBB",          "app.scrapers.bbb",         "BBBScraper"),
    "sulekha":     ("Sulekha",      "app.scrapers.sulekha",     "SulekhaScraper"),
    "linkedin":    ("LinkedIn",     "app.scrapers.linkedin",    "LinkedInScraper"),
    "facebook":    ("Facebook",     "app.scrapers.facebook",    "FacebookScraper"),
    "instagram":   ("Instagram",    "app.scrapers.instagram",   "InstagramScraper"),
    "twitter":     ("Twitter",      "app.scrapers.twitter",     "TwitterScraper"),
    "apollo":      ("Apollo.io",    "app.scrapers.apollo",      "ApolloScraper"),
}
ALL_SOURCES = list(SOURCES.keys())

# Default sources (no login needed)
DEFAULT_SOURCES = ["google", "yelp", "yellowpages", "bbb"]

# Social sources (require login)
SOCIAL_SOURCES = ["linkedin", "facebook", "instagram", "twitter"]

# API sources (require API key)
API_SOURCES = ["apollo"]


# ── EXACT column headers from LeadsFlow template ──────────────────────────────
# DO NOT change these — they must match leads_import_template.csv exactly

LEADSFLOW_COLUMNS = [
    # ── Required fields ───────────────────────────────────────────────────────
    "Name*",
    "Phone Number*",
    "Customer Category* (existing/potential)",
    "Lead Source* (website/referral/linkedin/facebook/twitter/instagram/campaign/generated_by/on_field/other)",
    "Lead Status* (new/followup/qualified/hot/converted/lost)",
    # ── Optional fields ───────────────────────────────────────────────────────
    "Email",
    "Date of Birth (YYYY-MM-DD)",
    "City",
    "State",
    "Country",
    "Pincode/Zipcode",
    "Company Name",
    "Designation",
    "Sector",
    "Custom Sector (if custom)",
    "Last Contacted Date (YYYY-MM-DD)",
    "Last Contacted By",
    "Next Followup Date (YYYY-MM-DD)",
    "Customer Interested In",
    "Preferred Communication Channel (email/phone/whatsapp/sms/in-person/linkedin/other)",
    "Custom Communication Channel (if other selected)",
    "Custom Lead Source (if other selected)",
    "Custom Referral Source (if referral selected)",
    "Custom Generated By (if generated_by selected)",
    "Lead Created By",
    "Additional Notes",
]

# ── Valid dropdown values (from template column hints) ────────────────────────

VALID_CATEGORIES  = {"existing", "potential"}
VALID_CHANNELS    = {"email", "phone", "whatsapp", "sms", "in-person", "linkedin", "other"}
VALID_SOURCES     = {"website", "referral", "linkedin", "facebook", "twitter",
                     "instagram", "campaign", "generated_by", "on_field", "other"}
VALID_STATUSES    = {"new", "followup", "qualified", "hot", "converted", "lost"}


# ── Text sanitization (for free-text fields only) ─────────────────────────────

def _sanitize(text: str, max_len: int = 100) -> str:
    """Only letters, spaces, and dots allowed in LeadsFlow text fields."""
    if not text:
        return ""
    text = text.encode("ascii", "ignore").decode("ascii")   # strip emojis/unicode
    subs = {"&": "and", "'": "", "\u2018": "", "\u2019": "", "\"": "",
            "|": ".", "/": " ", "\\": " ", ":": ".", ";": ".",
            ",": " ", "-": " ", "_": " ", "(": "", ")": "",
            "+": " ", "#": "", "@": " at ", "!": "", "?": "",
            "*": "", "%": " percent", "=": "", "<": "", ">": "",
            "[": "", "]": "", "{": "", "}": "", "~": "",
            "`": "", "^": "", "$": ""}
    for ch, rep in subs.items():
        text = text.replace(ch, rep)
    text = re.sub(r"[^a-zA-Z0-9 .]", "", text)
    text = re.sub(r" {2,}", " ", text).strip()
    return text[:max_len]


def _clean_phone(phone: str) -> str:
    """Digits and leading + only. Returns '' if invalid."""
    if not phone or phone.strip().upper() in ("N/A", "NA", "NONE", "-", ""):
        return ""
    digits = re.sub(r"[^\d\+]", "", phone).strip()
    return digits if len(digits) >= 7 else ""


def _map_source(sources: str) -> str:
    """Map scraper source names → valid LeadsFlow Lead Source value."""
    s = sources.lower()
    if "referral"   in s: return "referral"
    if "linkedin"   in s: return "linkedin"
    if "facebook"   in s: return "facebook"
    if "twitter"    in s: return "twitter"
    if "instagram"  in s: return "instagram"
    if "on_field"   in s or "field" in s: return "on_field"
    return "website"


def _map_channel(phone: str, email: str) -> str:
    """Map available contact info → valid LeadsFlow channel value."""
    if email:  return "email"
    if phone:  return "phone"
    return "email"


# ── Sector detection ─────────────────────────────────────────────────────────

SECTOR_HINTS = [
    (["plumb","hvac","roofer","electr","contractor","handyman","landscap","pest"],  "Capital Goods"),
    (["restaurant","cafe","food","bakery","catering","grocery","dairy","fmcg"],     "FMCG + Cold Chain"),
    (["doctor","dentist","clinic","hospital","pharma","therapy","wellness"],         "Pharmaceuticals"),
    (["lawyer","attorney","bank","finance","insurance","invest","tax","loan",
      "share","stock","broker","securities"],                                        "Financial Services"),
    (["school","college","university","academy","training","coaching"],              "Educational Institution"),
    (["real estate","realt","property","apartment","plot","builder","housing"],      "Real Estate"),
    (["interior","design","architect","decor","furnit"],                             "Interior Design"),
    (["solar","renewable","photovoltaic"],                                           "Industrials Solar"),
    (["transport","logistic","courier","freight","shipping","warehouse"],            "Logistics"),
    (["farm","agri","crop","seed","fertil","irrigation","poultry"],                 "Agriculture"),
    (["flour","mill","grain","wheat","roller"],                                      "Roller Flour Mills"),
    (["defence","defense","military","aerospace"],                                   "Defence"),
]

def _detect_sector_hint(name: str, category: str, keyword: str = "") -> str:
    text = f"{name} {category} {keyword}".lower()
    for kws, sector in SECTOR_HINTS:
        if any(k in text for k in kws):
            return sector
    return "Industrials"


# ── Core converter: Lead → LeadsFlow row dict ─────────────────────────────────

def lead_to_leadsflow(lead: Lead, keyword: str = "", country: str = "India") -> Optional[dict]:
    """
    Returns a dict with exact LeadsFlow template column keys.
    Returns None if mandatory fields (Name, Phone) are missing.
    """
    name  = _sanitize(lead.name, 100)
    phone = _clean_phone(lead.phone)

    if not name or not phone:
        return None   # mandatory fields missing — skip

    # Sector: use the user-selected sector (keyword) directly
    sector = keyword

    return {
        # ── Required fields ───────────────────────────────────────────────────
        "Name*":                            name,
        "Phone Number*":                    phone,
        "Customer Category* (existing/potential)":                                                                    "potential",
        "Lead Source* (website/referral/linkedin/facebook/twitter/instagram/campaign/generated_by/on_field/other)":   _map_source(lead.sources or ""),
        "Lead Status* (new/followup/qualified/hot/converted/lost)":                                                   "new",
        # ── Optional fields ───────────────────────────────────────────────────
        "Email":                            lead.email or "",
        "Date of Birth (YYYY-MM-DD)":       "",
        "City":                             _sanitize(lead.city, 50),
        "State":                            _sanitize(lead.state, 50),
        "Country":                          _sanitize(country, 50),
        "Pincode/Zipcode":                  re.sub(r"[^\d]", "", lead.zip_code or ""),
        "Company Name":                     _sanitize(getattr(lead, '_apollo_company', None) or name, 100),
        "Designation":                      "",
        "Sector":                           sector,
        "Custom Sector (if custom)":        "",
        "Last Contacted Date (YYYY-MM-DD)":                                                  "",
        "Last Contacted By":                                                                 "",
        "Next Followup Date (YYYY-MM-DD)":                                                   "",
        "Customer Interested In":                                                             "",
        "Preferred Communication Channel (email/phone/whatsapp/sms/in-person/linkedin/other)": _map_channel(phone, lead.email),
        "Custom Communication Channel (if other selected)":                                  "",
        "Custom Lead Source (if other selected)":                                            "",
        "Custom Referral Source (if referral selected)":                                     "",
        "Custom Generated By (if generated_by selected)":                                    "",
        "Lead Created By":                                                                   "",
        "Additional Notes":                                                                  "",
    }


# ── Deduplication ─────────────────────────────────────────────────────────────

def _norm(t: str) -> str:
    return re.sub(r"[^a-z0-9]", "", t.lower())

def deduplicate(leads: list) -> list:
    unique, phone_idx, name_idx = [], {}, {}
    for lead in leads:
        matched = None
        if lead.phone:
            d = re.sub(r"\D", "", lead.phone)
            if d and d in phone_idx: matched = phone_idx[d]
        if matched is None and lead.name and lead.city:
            key = _norm(lead.name) + "|" + _norm(lead.city)
            if key in name_idx: matched = name_idx[key]
        if matched is not None:
            unique[matched].merge(lead)
        else:
            idx = len(unique)
            unique.append(lead)
            if lead.phone:
                d = re.sub(r"\D", "", lead.phone)
                if d: phone_idx[d] = idx
            if lead.name and lead.city:
                name_idx[_norm(lead.name) + "|" + _norm(lead.city)] = idx
    return unique


# ── Main Engine ───────────────────────────────────────────────────────────────

# Sources whose data quality benefits from Google Maps enrichment
_ENRICHABLE_SOURCES = {"sulekha", "yellowpages", "yelp", "bbb"}


class LeadEngine:
    def __init__(self, sources=None, max_per_source=30, delay=1.5,
                 headless=True, min_score=0.0, country="India", enrich=True):
        self.sources        = sources or ALL_SOURCES
        self.max_per_source = max_per_source
        self.delay          = delay
        self.headless       = headless
        self.min_score      = min_score
        self.country        = country
        self.enrich         = enrich
        self.leads          = []
        self._keyword       = ""

    async def _run_one(self, source_key, keyword, location):
        if source_key not in SOURCES:
            return []
        label, module_path, class_name = SOURCES[source_key]
        print(f"  🔍  [{label}] Starting…")
        try:
            mod = importlib.import_module(module_path)
            cls = getattr(mod, class_name)
            leads = await cls(delay=self.delay).scrape(
                keyword, location, max_results=self.max_per_source, headless=self.headless)
            print(f"  ✅  [{label}] {len(leads)} found")
            return leads
        except Exception as e:
            print(f"  ❌  [{label}] {e}")
            return []

    async def run(self, keyword, location):
        import asyncio
        self._keyword = keyword
        print(f"\n{'═'*62}")
        print(f"  🚀  {keyword}  in  {location}")
        print(f"  Sources: {', '.join(self.sources)}  |  Max/src: {self.max_per_source}")
        print(f"{'═'*62}\n")

        enrichable = _ENRICHABLE_SOURCES.intersection(self.sources)
        should_enrich = self.enrich and bool(enrichable)

        # Tag each task with its source key so we know which results are enrichable
        async def _run_tagged(src):
            leads = await self._run_one(src, keyword, location)
            return src, leads

        scrape_tasks = [
            asyncio.create_task(_run_tagged(src)) for src in self.sources
        ]

        all_raw: list = []
        enrich_tasks: list = []

        if should_enrich:
            from app.scrapers.enrichment import LeadEnrichmentPipeline
            pipeline = LeadEnrichmentPipeline(delay=self.delay, concurrency=8)
            print(f"  →  enriching as sources complete…", flush=True)
            try:
                async with pipeline.stream(headless=self.headless) as enrich_fn:
                    # Process each source the moment it finishes
                    for coro in asyncio.as_completed(scrape_tasks):
                        src, leads = await coro
                        all_raw.extend(leads)
                        if leads and src in enrichable:
                            # Fire-and-forget enrichment task; browser stays open
                            t = asyncio.create_task(enrich_fn(leads))
                            enrich_tasks.append(t)
                    # Wait for all in-flight enrichment before closing browser
                    if enrich_tasks:
                        await asyncio.gather(*enrich_tasks)
            except Exception as exc:
                print(f"  ⚠️   enrichment skipped ({exc})")
        else:
            results = await asyncio.gather(*scrape_tasks)
            for _src, leads in results:
                all_raw.extend(leads)

        print(f"\n  📦  Raw: {len(all_raw)}  →  dedup: ", end="")
        unique = deduplicate(all_raw)
        print(len(unique), end="")

        if should_enrich and enrich_tasks:
            # Post-enrichment dedup (phone/website/address keys)
            from app.scrapers.enrichment import LeadEnrichmentPipeline
            unique = LeadEnrichmentPipeline._deduplicate(unique)
            enriched_count = sum(1 for l in unique if l.enriched_from)
            print(f"  →  enriched: {enriched_count}", end="")

        print(f"  →  ranked: ", end="")
        self.leads = rank_leads(unique, min_score=self.min_score)
        print(len(self.leads))
        return self.leads

    # ── Build dataframe ────────────────────────────────────────────────────────

    def _build_rows(self):
        rows, skipped = [], 0
        for l in self.leads:
            row = lead_to_leadsflow(l, keyword=self._keyword, country=self.country)
            if row: rows.append(row)
            else:   skipped += 1
        if skipped:
            print(f"  ⚠️   {skipped} leads skipped (missing phone or name)")
        return rows

    # ── CSV export (primary format for LeadsFlow import) ──────────────────────

    def to_csv(self, filepath: str) -> str:
        rows = self._build_rows()
        if not rows: return ""
        path = Path(filepath)
        with open(path, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=LEADSFLOW_COLUMNS)
            writer.writeheader()
            writer.writerows(rows)
        print(f"  💾  CSV  → {path.resolve()}  ({len(rows)} leads)")
        return str(path.resolve())

    # ── Excel export (for review before uploading) ────────────────────────────

    def to_excel(self, filepath: str) -> str:
        if not HAS_PANDAS:
            print("❌  pip install pandas openpyxl"); return ""
        rows = self._build_rows()
        if not rows: return ""
        path = Path(filepath)
        df = pd.DataFrame(rows, columns=LEADSFLOW_COLUMNS)

        import openpyxl
        with pd.ExcelWriter(path, engine="openpyxl") as writer:
            df.to_excel(writer, index=False, sheet_name="LeadsFlow Import")
            ws = writer.sheets["LeadsFlow Import"]
            hfill = PatternFill(start_color="1F4E79", end_color="1F4E79", fill_type="solid")
            hfont = Font(bold=True, color="FFFFFF", name="Arial", size=9)
            for cell in ws[1]:
                cell.fill = hfill; cell.font = hfont
                cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
            ws.row_dimensions[1].height = 42
            alt = [PatternFill(start_color="F8F9FA", end_color="F8F9FA", fill_type="solid"),
                   PatternFill(start_color="FFFFFF", end_color="FFFFFF", fill_type="solid")]
            bfont  = Font(name="Arial", size=9)
            border = Border(bottom=Side(style="thin", color="DDDDDD"))
            for i, row in enumerate(ws.iter_rows(min_row=2, max_row=ws.max_row), 1):
                fill = alt[i % 2]
                for cell in row:
                    cell.fill = fill; cell.font = bfont
                    cell.border = border
                    cell.alignment = Alignment(vertical="top")
            for col in ws.columns:
                w = max(len(str(c.value or "")) for c in col)
                ws.column_dimensions[col[0].column_letter].width = min(w+3, 40)
            ws.freeze_panes = "A2"

        print(f"  💾  Excel → {path.resolve()}  ({len(rows)} leads)")
        return str(path.resolve())

    def print_summary(self, top_n=20):
        if not self.leads: print("No leads."); return
        print(f"\n{'─'*75}")
        print(f"{'#':<4} {'Name':<30} {'Phone':<16} {'City'}")
        print(f"{'─'*75}")
        for i, l in enumerate(self.leads[:top_n], 1):
            print(f"{i:<4} {l.name[:28]:<30} {(l.phone or ''):<16} {l.city or ''}")
        if len(self.leads) > top_n:
            print(f"  … and {len(self.leads)-top_n} more in export file.")

    def print_top_scorecards(self, n=3):
        """No-op: scoring removed."""
        pass
